const CACHE='spanish-zero-web-v21-background-media';
const SHELL=['/','/index.html','/manifest.webmanifest','/icon-192.png','/icon-512.png'];
const LOOP_SCRIPT=String.raw`(()=>{
let running=false,runId=0,deck=[],source='';const N=1200;
const F=/female|woman|mujer|helena|elvira|lucia|lucía|paulina|monica|mónica|sofia|sofía|maria|maría|irina|svetlana|victoria/i;
const M=/male|man|hombre|alvaro|álvaro|pablo|diego|jorge|antonio|pavel|yuri|alexander|maxim|dmitry|nikolai|mikhail/i;
const p=()=>{try{return typeof getP==='function'?getP():{dictSelected:[]}}catch{return{dictSelected:[]}}},all=()=>{try{return typeof dictionaryEntries==='function'?dictionaryEntries():[]}catch{return[]}};
function cat(){try{if(typeof dictCategory!=='undefined'&&dictCategory)return dictCategory}catch{}return document.querySelector('select.category-select')?.value||'all'}
function v(lang,g){let c=lang.slice(0,2),a=speechSynthesis.getVoices().filter(x=>(x.lang||'').toLowerCase().startsWith(c)),r=g==='female'?F:M;return a.find(x=>r.test(x.name||''))||(a.length>1?a[g==='female'?0:1]:a[0]||null)}
function u(t,l,g,r){let x=new SpeechSynthesisUtterance(t);x.lang=l;x.rate=r;let q=v(l,g);if(q)x.voice=q;return x}
function gap(g){let x=u('pausa pausa pausa','es-ES',g,.5);x.volume=0;return x}
function selectedIds(){let x=p().dictSelected;return Array.isArray(x)?x:[]}
function categoryWords(){let a=all(),c=cat();return c==='all'?a:a.filter(x=>x.category===c)}
function refresh(){let sb=document.getElementById('listen-selected-btn'),cb=document.getElementById('listen-category-btn'),db=document.getElementById('loop-card-btn'),s=document.getElementById('selected-loop-status'),n=selectedIds().length,c=cat(),k=categoryWords().length;
if(sb){sb.disabled=!n&&!running;sb.style.opacity=(n||running)?'1':'.45';sb.textContent=running?'■ Остановить':('▶ Прослушать выбранное ('+n+')')}
if(cb){cb.disabled=false;cb.style.opacity='1';cb.textContent=running?'■ Остановить':(c==='all'?('🔁 Прослушать весь словарь ('+k+')'):('🔁 Прослушать категорию ('+k+')'))}
if(db){db.disabled=false;db.style.opacity='1';db.textContent=running?'■ Остановить':'▶ Прослушать выбранное'}
if(s)s.textContent=running?'Идёт по кругу: '+deck.length+' слов · '+source+'. Пауза 3 секунды. Голоса чередуются.':n?'Выбрано галками: '+n+' слов. Можно слушать их отдельно или запустить всю категорию.':c==='all'?'Галок нет. Можно слушать весь словарь.':'Галок нет. Можно слушать категорию «'+c+'».'}
function ensure(){let a=document.querySelector('.dict-actions');if(a){let sb=document.getElementById('listen-selected-btn');if(!sb){sb=document.createElement('button');sb.id='listen-selected-btn';sb.className='accent';a.appendChild(sb)}sb.onclick=()=>toggle('selected');let cb=document.getElementById('listen-category-btn');if(!cb){cb=document.createElement('button');cb.id='listen-category-btn';a.appendChild(cb)}cb.onclick=()=>toggle('category');let s=document.getElementById('selected-loop-status');if(!s){s=document.createElement('div');s.id='selected-loop-status';s.className='muted tiny';s.style.margin='-4px 2px 12px';a.insertAdjacentElement('afterend',s)}}
let db=document.getElementById('loop-card-btn'),isDrill=false;try{isDrill=typeof page!=='undefined'&&page==='drill'}catch{}if(isDrill){let main=document.querySelector('main');if(main&&!db){db=document.createElement('button');db.id='loop-card-btn';db.className='primary';db.style.marginTop='12px';db.onclick=()=>toggle('card');let nav=main.querySelector('.drill-nav');if(nav)nav.insertAdjacentElement('afterend',db);else main.appendChild(db)}}else if(db)db.remove();refresh()}
function stop(){running=false;runId++;deck=[];source='';if('speechSynthesis'in window)speechSynthesis.cancel();refresh()}
function card(w,i){try{drillDeck=deck.slice();drillPos=i;page='drill';lastAutoSpoken=w.id+':'+i;render();ensure()}catch{}}
function queue(id){for(let t=0;t<N&&running&&id===runId;t++){let i=t%deck.length,w=deck[i],f=t%2===0,eg=f?'female':'male',rg=f?'male':'female',es=u(w.es,'es-ES',eg,.70),ru=u(w.ru,'ru-RU',rg,.79),g=gap(eg);es.onstart=()=>{if(running&&id===runId)card(w,i)};speechSynthesis.speak(es);speechSynthesis.speak(ru);speechSynthesis.speak(g)}}
function chooseDeck(mode){let a=all();if(mode==='card'){try{if(Array.isArray(drillDeck)&&drillDeck.length){deck=drillDeck.slice();source='текущий набор карточек';return}}catch{}}if(mode==='selected'){let ids=selectedIds();deck=a.filter(x=>ids.includes(x.id));source='выбранные галками слова';return}let c=cat();deck=c==='all'?a:a.filter(x=>x.category===c);source=c==='all'?'весь словарь':'категория «'+c+'»'}
function toggle(mode){if(running)return stop();chooseDeck(mode);if(!deck.length){if(mode==='selected')return alert('Сначала отметьте слова галками в словаре.');return alert('В выбранном наборе нет слов.')}if(!('speechSynthesis'in window))return alert('Озвучка не поддерживается.');speechSynthesis.cancel();running=true;let id=++runId;card(deck[0],0);setTimeout(()=>queue(id),80);refresh()}
window.startSelectedListening=()=>toggle('selected');window.startCategoryListening=()=>toggle('category');window.startLoopListening=fromCard=>toggle(fromCard?'card':'category');window.stopSelectedLoopListening=stop;
let app=document.getElementById('app');if(app)new MutationObserver(()=>setTimeout(ensure,0)).observe(app,{childList:true});ensure();
})();`;
const MOBILE=String.raw`<style id="mobile-dictionary-fix">@media(max-width:520px){
.dict-table-wrap{overflow-x:auto!important;-webkit-overflow-scrolling:touch!important;border:1px solid #e9dfd2!important;border-radius:16px!important;background:#fff!important}
.dict-table{display:table!important;width:100%!important;min-width:760px!important;border-collapse:collapse!important;table-layout:auto!important;font-size:.82rem!important}
.dict-table thead{display:table-header-group!important}.dict-table tbody{display:table-row-group!important}.dict-table tr{display:table-row!important}.dict-table th,.dict-table td{display:table-cell!important;padding:8px 7px!important;border-bottom:1px solid #f0e9e0!important;white-space:nowrap!important;vertical-align:middle!important}
.dict-table th:nth-child(1),.dict-table td:nth-child(1){position:sticky!important;left:0!important;z-index:3!important;width:54px!important;min-width:54px!important;text-align:center!important;background:#fff!important}
.dict-table th:nth-child(2),.dict-table td:nth-child(2){position:sticky!important;left:54px!important;z-index:2!important;min-width:135px!important;background:#fff!important}
.dict-table th:nth-child(3),.dict-table td:nth-child(3){min-width:145px!important}.dict-table th:nth-child(4),.dict-table td:nth-child(4){min-width:150px!important}.dict-table th:nth-child(5),.dict-table td:nth-child(5){min-width:130px!important}.dict-table th:nth-child(6),.dict-table td:nth-child(6){min-width:76px!important}.dict-table th:nth-child(7),.dict-table td:nth-child(7){min-width:50px!important}
.dict-table .hide-small{display:table-cell!important}.dict-es{display:block!important;font-size:1rem!important;font-weight:900!important;color:#231f20!important}.dict-tr{display:block!important;color:#985819!important}.dict-ru{display:block!important}.dict-no{display:block!important}
:root[data-theme="dark"] .dict-table-wrap{background:#1b1e22!important;border-color:#34383f!important}:root[data-theme="dark"] .dict-table th:nth-child(1),:root[data-theme="dark"] .dict-table td:nth-child(1),:root[data-theme="dark"] .dict-table th:nth-child(2),:root[data-theme="dark"] .dict-table td:nth-child(2){background:#1b1e22!important}:root[data-theme="dark"] .dict-es{color:#fff!important}
#listen-selected-btn,#listen-category-btn,#loop-card-btn{display:inline-flex!important;visibility:visible!important}
}</style>`;
function prep(h){h=h.replace('const BASE_WORDS=buildExtendedDictionary(CORE_WORDS);','const BASE_WORDS=CORE_WORDS.map(x=>({...x}));');if(!h.includes('mobile-dictionary-fix'))h=h.replace('</head>',MOBILE+'</head>');if(!h.includes('listen-selected-btn'))h=h.replace('<div class="dict-actions"><button onclick="selectVisible()">✓ Выбрать показанные</button><button onclick="clearSelection()">Снять выбор</button></div>','<div class="dict-actions"><button onclick="selectVisible()">✓ Выбрать показанные</button><button onclick="clearSelection()">Снять выбор</button><button id="listen-selected-btn" class="accent" onclick="startSelectedListening()">▶ Прослушать выбранное (0)</button><button id="listen-category-btn" onclick="startCategoryListening()">🔁 Прослушать категорию</button></div><div id="selected-loop-status" class="muted tiny" style="margin:-4px 2px 12px"></div>');if(!h.includes('window.startSelectedListening'))h=h.replace('</body>','<script>'+LOOP_SCRIPT+'<\/script></body>');return h}
async function page(req){try{let r=await fetch(req,{cache:'no-store'});if(!(r.headers.get('content-type')||'').includes('text/html'))return r;let h=prep(await r.text()),hd=new Headers(r.headers);hd.delete('content-length');let m=new Response(h,{status:r.status,statusText:r.statusText,headers:hd});caches.open(CACHE).then(c=>c.put('/index.html',m.clone()));return m}catch{let r=await caches.match('/index.html'),h=prep(await r.text()),hd=new Headers(r.headers);hd.delete('content-length');return new Response(h,{status:r.status,statusText:r.statusText,headers:hd})}}
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)))});
self.addEventListener('activate',e=>e.waitUntil((async()=>{let k=await caches.keys();await Promise.all(k.filter(x=>x!==CACHE).map(x=>caches.delete(x)));await self.clients.claim();let cs=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(let c of cs){try{let u=new URL(c.url);if(u.searchParams.get('app_update')!=='21'){u.searchParams.set('app_update','21');await c.navigate(u.toString())}}catch{}}})()));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{let r=e.request;if(r.method!=='GET')return;if(r.mode==='navigate')return e.respondWith(page(r));e.respondWith(caches.match(r).then(x=>x||fetch(r).then(y=>{caches.open(CACHE).then(c=>c.put(r,y.clone()));return y}))) });