const CACHE='spanish-zero-web-v13-button-spanish-first';
const SHELL=['/','/index.html','/manifest.webmanifest','/icon-192.png','/icon-512.png'];
const LOOP_SCRIPT=String.raw`(()=>{
let running=false,runId=0,deck=[],source='';const N=1200;
const F=/female|woman|mujer|helena|elvira|lucia|lucía|paulina|monica|mónica|sofia|sofía|maria|maría|irina|svetlana|victoria/i;
const M=/male|man|hombre|alvaro|álvaro|pablo|diego|jorge|antonio|pavel|yuri|alexander|maxim|dmitry|nikolai|mikhail/i;
const p=()=>{try{return typeof getP==='function'?getP():{dictSelected:[]}}catch{return{dictSelected:[]}}},all=()=>{try{return typeof dictionaryEntries==='function'?dictionaryEntries():[]}catch{return[]}};
function cat(){try{if(typeof dictCategory!=='undefined'&&dictCategory)return dictCategory}catch{}return document.querySelector('select.category-select')?.value||'all'}
function v(lang,g){let c=lang.slice(0,2),a=speechSynthesis.getVoices().filter(x=>(x.lang||'').toLowerCase().startsWith(c)),r=g==='female'?F:M;return a.find(x=>r.test(x.name||''))||(a.length>1?a[g==='female'?0:1]:a[0]||null)}
function u(t,l,g,r){let x=new SpeechSynthesisUtterance(t);x.lang=l;x.rate=r;let q=v(l,g);if(q)x.voice=q;return x}
function gap(g){let x=u('pausa pausa pausa','es-ES',g,.5);x.volume=0;return x}
function count(){let x=p().dictSelected;return Array.isArray(x)?x.length:0}
function categoryWords(){let a=all(),c=cat();return c==='all'?a:a.filter(x=>x.category===c)}
function refresh(){let b=document.getElementById('selected-loop-btn'),s=document.getElementById('selected-loop-status'),n=count(),c=cat(),k=categoryWords().length;if(b){b.disabled=false;b.style.opacity='1';b.textContent=running?'■ Остановить прослушку':n?'🔁 Прослушка по кругу ('+n+')':'🔁 Прослушка по кругу · '+(c==='all'?'весь словарь':c)+' ('+k+')'}if(s)s.textContent=running?'Идёт по кругу: '+deck.length+' слов · '+source+'. Пауза 3 секунды. Голоса чередуются.':n?'Будут звучать отмеченные слова.':c==='all'?'Галки не выбраны — будет звучать весь словарь.':'Галки не выбраны — будет звучать категория «'+c+'».'}
function ensure(){let a=document.querySelector('.dict-actions'),b=document.getElementById('selected-loop-btn');if(a&&!b){b=document.createElement('button');b.id='selected-loop-btn';b.className='accent';b.textContent='🔁 Прослушка по кругу';a.appendChild(b)}if(b)b.onclick=toggle;let s=document.getElementById('selected-loop-status');if(a&&!s){s=document.createElement('div');s.id='selected-loop-status';s.className='muted tiny';s.style.margin='-4px 2px 12px';a.insertAdjacentElement('afterend',s)}refresh()}
function stop(){running=false;runId++;deck=[];source='';speechSynthesis.cancel();refresh()}
function card(w,i){try{drillDeck=deck.slice();drillPos=i;page='drill';lastAutoSpoken=w.id+':'+i;render();ensure()}catch{}}
function queue(id){for(let t=0;t<N&&running&&id===runId;t++){let i=t%deck.length,w=deck[i],f=t%2===0,eg=f?'female':'male',rg=f?'male':'female',es=u(w.es,'es-ES',eg,.70),ru=u(w.ru,'ru-RU',rg,.79),g=gap(eg);es.onstart=()=>{if(running&&id===runId)card(w,i)};speechSynthesis.speak(es);speechSynthesis.speak(ru);speechSynthesis.speak(g)}}
function toggle(){if(running)return stop();let pr=p(),sel=Array.isArray(pr.dictSelected)?pr.dictSelected:[],a=all();if(sel.length){deck=a.filter(x=>sel.includes(x.id));source='отмеченные слова'}else{let c=cat();deck=c==='all'?a:a.filter(x=>x.category===c);source=c==='all'?'весь словарь':'категория «'+c+'»'}if(!deck.length)return alert('В выбранной категории нет слов.');if(!('speechSynthesis'in window))return alert('Озвучка не поддерживается.');speechSynthesis.cancel();running=true;let id=++runId;card(deck[0],0);setTimeout(()=>queue(id),80);refresh()}
window.startLoopListening=toggle;window.stopSelectedLoopListening=stop;
let app=document.getElementById('app');if(app)new MutationObserver(()=>setTimeout(ensure,0)).observe(app,{childList:true});ensure();
})();`;
const MOBILE=String.raw`<style id="mobile-dictionary-fix">@media(max-width:520px){
.dict-table-wrap{overflow-x:hidden!important;border:0!important;background:transparent!important}
.dict-table{display:block!important;min-width:0!important;width:100%!important;background:transparent!important}
.dict-table thead{display:none!important}.dict-table tbody{display:block!important;width:100%!important}
.dict-table tr{display:grid!important;grid-template-columns:1fr 48px!important;grid-template-areas:'es check' 'tr tr' 'ru ru'!important;gap:4px 8px!important;width:100%!important;margin:0 0 10px!important;padding:12px!important;border:1px solid #e9dfd2!important;border-radius:14px!important;background:#fff!important}
:root[data-theme="dark"] .dict-table tr{background:#1b1e22!important;border-color:#34383f!important}
.dict-table td{display:block!important;width:auto!important;padding:0!important;border:0!important;white-space:normal!important;overflow-wrap:anywhere!important}
.dict-table td:nth-child(2){grid-area:es!important}.dict-table td:nth-child(1){grid-area:check!important;display:flex!important;align-items:flex-start!important;justify-content:flex-end!important}.dict-table td:nth-child(3){grid-area:tr!important}.dict-table td:nth-child(4){grid-area:ru!important}.dict-table td:nth-child(n+5){display:none!important}
.dict-es{display:block!important;font-size:1.25rem!important;font-weight:900!important;line-height:1.2!important;color:#231f20!important}.dict-tr{display:block!important;font-size:.85rem!important;color:#985819!important}.dict-ru{display:block!important;font-size:.9rem!important;color:#4e4741!important}.dict-no{display:none!important}:root[data-theme="dark"] .dict-es{color:#fff!important}:root[data-theme="dark"] .dict-ru{color:#ddd6ce!important}
#selected-loop-btn{display:inline-flex!important;visibility:visible!important;opacity:1!important}
}</style>`;
function prep(h){h=h.replace('const BASE_WORDS=buildExtendedDictionary(CORE_WORDS);','const BASE_WORDS=CORE_WORDS.map(x=>({...x}));');if(!h.includes('mobile-dictionary-fix'))h=h.replace('</head>',MOBILE+'</head>');if(!h.includes('selected-loop-btn'))h=h.replace('<div class="dict-actions"><button onclick="selectVisible()">✓ Выбрать показанные</button><button onclick="clearSelection()">Снять выбор</button></div>','<div class="dict-actions"><button onclick="selectVisible()">✓ Выбрать показанные</button><button onclick="clearSelection()">Снять выбор</button><button id="selected-loop-btn" class="accent" onclick="startLoopListening()">🔁 Прослушка по кругу</button></div><div id="selected-loop-status" class="muted tiny" style="margin:-4px 2px 12px"></div>');if(!h.includes('window.startLoopListening=toggle'))h=h.replace('</body>','<script>'+LOOP_SCRIPT+'<\\/script></body>');return h}
async function page(req){try{let r=await fetch(req,{cache:'no-store'});if(!(r.headers.get('content-type')||'').includes('text/html'))return r;let h=prep(await r.text()),hd=new Headers(r.headers);hd.delete('content-length');let m=new Response(h,{status:r.status,statusText:r.statusText,headers:hd});caches.open(CACHE).then(c=>c.put('/index.html',m.clone()));return m}catch{let r=await caches.match('/index.html'),h=prep(await r.text()),hd=new Headers(r.headers);hd.delete('content-length');return new Response(h,{status:r.status,statusText:r.statusText,headers:hd})}}
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)))});
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data?.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{let r=e.request;if(r.method!=='GET')return;if(r.mode==='navigate')return e.respondWith(page(r));e.respondWith(caches.match(r).then(x=>x||fetch(r).then(y=>{caches.open(CACHE).then(c=>c.put(r,y.clone()));return y}))) });
